{% set name = "compadre" %}
{% set version = "1.0.34" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

requirements:
  host:
    - numpy {{ numpy }}
    - python {{ python }}
    - "cmake>=3.10.0"
    - pathlib2
    - wheel
    - pip
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - compadre

about:
  home: https://github.com/SNLComputation/compadre
  license: BSD
  license_family: BSD
  license_file: LICENSE.md
  summary: COMpatible PArticle Discretization and REmap Toolkit
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - kuberry
